apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.19
              ports:
              - containerPort: 80
              resources:
                requests:
                  memory: 100M
                  cpu: 100m
                limits:
                  memory: 250M
                  cpu: 150m                

                

