apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    - containerPort: 3307
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: contraseña
    - name: MYSQL_USER
      value: microservice
