apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: nginx-statefulset
spec:
    selector:
        matchLabels:
            app: nginx-statefulset
    serviceName: nginx-statefulset
    replicas: 3
    template:
        metadata:
            labels:
                app: nginx-statefulset
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80